In [1]:
import numpy as np
np.__version__

'1.20.3'

In [2]:
import array
lst = list(range(10))
A = array.array('i',lst)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [5]:
np.array([1.0,3,5,7,9])

array([1., 3., 5., 7., 9.])

In [6]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [7]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((3,5), 3.11)

array([[3.11, 3.11, 3.11, 3.11, 3.11],
       [3.11, 3.11, 3.11, 3.11, 3.11],
       [3.11, 3.11, 3.11, 3.11, 3.11]])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.random.random((3,3))

array([[0.11202292, 0.79986305, 0.25286529],
       [0.07221142, 0.38686021, 0.58311592],
       [0.8354021 , 0.43913584, 0.77547288]])

In [15]:
np.random.normal(0,1,(3,3))

array([[-0.08548861,  1.43979787,  0.06526579],
       [ 1.04803827,  0.3600807 ,  0.29527368],
       [-0.27679284,  1.62682355, -0.12203708]])

In [16]:
np.random.randint(0,10,(3,3))

array([[9, 4, 7],
       [0, 9, 1],
       [3, 3, 2]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.empty(3)

array([1., 1., 1.])