# Numpy Array Attribute

In [1]:
import numpy as np

In [2]:
np.random.seed(10)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [3]:
print('x3 ndim: ', x3.ndim)
print('x3 shape: ',x3.shape)
print('x3 size: ',x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [4]:
print('x3 dtype: ',x3.dtype)

x3 dtype:  int32


In [5]:
print('x3 itemsize: ',x3.itemsize)
print('x3 nbytes: ',x3.nbytes)

x3 itemsize:  4
x3 nbytes:  240


# Array Indexing

In [6]:
x1

array([9, 4, 0, 1, 9, 0])

In [7]:
x1[0]

9

In [8]:
x1[3]

1

In [9]:
x1[-1]

0

In [10]:
x1[-2]

9

In [11]:
x2

array([[1, 8, 9, 0],
       [8, 6, 4, 3],
       [0, 4, 6, 8]])

In [12]:
x2[0,0]

1

In [13]:
x2[2,1]

4

In [14]:
x2[2,-1]

8

In [15]:
x2[0,0] = 8

In [16]:
x2

array([[8, 8, 9, 0],
       [8, 6, 4, 3],
       [0, 4, 6, 8]])

In [17]:
x1[0] = 2.345

In [18]:
x1

array([2, 4, 0, 1, 9, 0])

# Array Slicing

In [20]:
x = np.arange(10)

In [21]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[:4]

array([0, 1, 2, 3])

In [23]:
x[4:]

array([4, 5, 6, 7, 8, 9])

In [24]:
x[4:8]

array([4, 5, 6, 7])

In [25]:
x[::2]

array([0, 2, 4, 6, 8])

In [26]:
x[1::2]

array([1, 3, 5, 7, 9])

In [27]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
x[5::-2]

array([5, 3, 1])

In [29]:
x2

array([[8, 8, 9, 0],
       [8, 6, 4, 3],
       [0, 4, 6, 8]])

In [30]:
x2[:2, :3]

array([[8, 8, 9],
       [8, 6, 4]])

In [31]:
x2[:2, ::2]

array([[8, 9],
       [8, 4]])

In [32]:
x2[::-1, ::-1]

array([[8, 6, 4, 0],
       [3, 4, 6, 8],
       [0, 9, 8, 8]])

In [33]:
print(x2[:, 0])

[8 8 0]


In [34]:
print(x2[0,:1])

[8]


In [35]:
print(x2[0])

[8 8 9 0]


In [36]:
x2

array([[8, 8, 9, 0],
       [8, 6, 4, 3],
       [0, 4, 6, 8]])

In [37]:
print(x2)

[[8 8 9 0]
 [8 6 4 3]
 [0 4 6 8]]


In [38]:
x2_sub = x2[:2, :2]

In [39]:
x2_sub

array([[8, 8],
       [8, 6]])

In [40]:
x2_sub[0,0] = 4

In [41]:
print(x2_sub)

[[4 8]
 [8 6]]


In [42]:
print(x2)

[[4 8 9 0]
 [8 6 4 3]
 [0 4 6 8]]


In [43]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[4 8]
 [8 6]]


In [44]:
x2_sub_copy[0,0]=7
print(x2_sub_copy)

[[7 8]
 [8 6]]


In [45]:
print(x2)

[[4 8 9 0]
 [8 6 4 3]
 [0 4 6 8]]


# Reshaping of Arrays

In [46]:
grid = np.arange(1,10).reshape(3,3)

In [47]:
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
x = np.array([1,2,3])
x.reshape(1,3)

array([[1, 2, 3]])

In [49]:
x

array([1, 2, 3])

In [50]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [51]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [52]:
x

array([1, 2, 3])

In [53]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

# Concatenation and Spliting

In [54]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [55]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [56]:
z = [4,5,6]
print(np.concatenate([x,y,z]))

[1 2 3 3 2 1 4 5 6]


In [57]:
grid = np.array([[1,2,3],
                 [4,5,6]])

In [58]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [61]:
x = np.array([9,8,7])
grid = np.array([[1,2,3],
                [4,5,6]])
np.vstack([x,grid])

array([[9, 8, 7],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
y = np.array([[99],
              [99]])
np.hstack([grid,y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [69]:
x = [4,5,6,88,88,7,8,9]
x1, x2, x3 = np.split(x, [3,7])
print(x1,x2,x3)

[4 5 6] [88 88  7  8] [9]


In [70]:
grid = np.arange(16).reshape(4,4)

In [71]:
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [72]:
upper, lower = np.vsplit(grid,2)
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [73]:
left, right = np.hsplit(grid, 2)
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
