# Summing the values in an Array

In [1]:
import numpy as np

In [2]:
lst = np.random.random(100)
sum(lst)

53.625292751830855

In [3]:
np.sum(lst)

53.62529275183084

In [4]:
big_array = np.random.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

187 ms ± 2.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.44 ms ± 44.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
min(big_array), max(big_array)

(2.088313606596337e-06, 0.9999988447222616)

In [6]:
%timeit min(big_array)
%timeit np.min(big_array)

125 ms ± 2.73 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
822 µs ± 13 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
print(big_array.min(), big_array.max(), big_array.sum())

2.088313606596337e-06 0.9999988447222616 500108.0801763925


In [8]:
matrix = np.random.random((3,4))
print(matrix)

[[0.84641264 0.35425265 0.91144604 0.51771023]
 [0.14504197 0.98178157 0.62777693 0.55070649]
 [0.73069424 0.3808205  0.25405406 0.29215425]]


In [9]:
matrix.sum()

6.592851581517328

In [10]:
matrix.min(axis=0)

array([0.14504197, 0.35425265, 0.25405406, 0.29215425])

In [12]:
matrix.max(axis=1)

array([0.91144604, 0.98178157, 0.73069424])

In [13]:
np.prod(matrix)

0.00014386045228633658

In [14]:
np.mean(matrix)

0.5494042984597773

In [15]:
np.std(matrix)

0.26294418260399455

In [16]:
np.var(matrix)

0.06913964316528283

In [17]:
np.argmin(matrix)

4

In [18]:
np.any(matrix)

True

In [19]:
np.all(matrix)

True