In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
x < 3

array([ True,  True, False, False, False])

In [4]:
x>3

array([False, False, False,  True,  True])

In [5]:
x <=3 

array([ True,  True,  True, False, False])

In [6]:
x >= 3

array([False, False,  True,  True,  True])

In [7]:
x != 3

array([ True,  True, False,  True,  True])

In [8]:
x == 3

array([False, False,  True, False, False])

In [9]:
(2*x) == (x**2)

array([False,  True, False, False, False])

In [10]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [11]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [12]:
np.count_nonzero(x<5)

6

In [13]:
np.sum(x<5)

6

In [14]:
np.sum(x<5, axis=1)

array([3, 1, 2])

In [15]:
np.any(x>8)

True

In [16]:
np.any(x<8)

True

In [18]:
np.all(x<8, axis=1)

array([ True, False,  True])

In [28]:
inches = np.arange(5)
print(inches)

[0 1 2 3 4]


In [29]:
np.sum((inches > 2) & (inches<5))

2

In [30]:
np.sum(~((inches<=2)|(inches>=5)))

2

In [35]:
x = rng.randint(10, size=(3,4))
print(x)

[[4 3 0 3]
 [5 0 2 3]
 [8 1 3 3]]


In [36]:
x < 5

array([[ True,  True,  True,  True],
       [False,  True,  True,  True],
       [False,  True,  True,  True]])

In [37]:
x[x<5]

array([4, 3, 0, 3, 0, 2, 3, 1, 3, 3])

In [38]:
bool(30), bool(0)

(True, False)

In [39]:
bool(30 and 0)

False

In [40]:
bool(30 or 0)

True

In [41]:
bin(30)

'0b11110'

In [42]:
bin(15)

'0b1111'

In [43]:
bin(30 & 15)

'0b1110'

In [44]:
bin(30 | 15)

'0b11111'

In [45]:
a = np.array([1,0,0,1,1,0], dtype=bool)
b = np.array([1,1,0,0,1,0], dtype=bool)
a | b

array([ True,  True, False,  True,  True, False])

In [46]:
a or b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [47]:
x = np.arange(10)
(x>4) & (x<8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [48]:
(x>4) and (x<8)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()